s = set()
n = input("enter the num: ")
s.add(int(n))
n = input("enter the num: ")
s.add(int(n))
n = input("enter the num: ")
s.add(int(n))
n = input("enter the num: ")
s.add(int(n))
n = input("enter the num: ")
s.add(int(n))
n = input("enter the num: ")
s.add(int(n))
n = input("enter the num: ")
s.add(int(n))
n = input("enter the num: ")
s.add(int(n))
print(s)